# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      TEST_CMD: "py.test test_env.py"

  matrix:
        # Note that setting CONDA_CHANNEL_PRIORITY in the next two builds is
        # unrelated to the rest of the builds and won't change anything, except
        # that we can make sure the conda config was correctly updated.

      - PYTHON_VERSION: "2.7"
        DEBUG: "True"
        PYTEST_VERSION: "<4"
        TEST_CMD: "python -c \"import pytest; assert int(pytest.__version__[0])<4\""

matrix:
   fast_finish: true

platform:
    -x64

#os: Visual Studio 2015 Update 2

install:

    # Install Miniconda
    - "git clone . ci-helpers"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"

    # Set path again, need to find a way to avoid doing this again
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

    # Test that PATH is set correctly
    - "conda --version"
    - "python --version"

# Not a .NET project, we build ci-helpers in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% %TEST_CMD%"
